/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DailyPlan: typeof import('./src/components/NanHua/DailyPlan.vue')['default']
    FunctionInfo: typeof import('./src/components/FunctionInfo.vue')['default']
    NDivider: typeof import('naive-ui')['NDivider']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    Root: typeof import('./src/components/Root.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    YBInstall: typeof import('./src/components/YBProcessDoc/YBInstall.vue')['default']
  }
}
