/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DailyPlan: typeof import('./src/components/NanHua/DailyPlan.vue')['default']
    FunctionInfo: typeof import('./src/components/FunctionInfo.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NButton: typeof import('naive-ui')['NButton']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NDivider: typeof import('naive-ui')['NDivider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NTable: typeof import('naive-ui')['NTable']
    Root: typeof import('./src/components/Root.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    YBInstall: typeof import('./src/components/YBProcessDoc/YBInstall.vue')['default']
  }
}
